// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ChooseXPlanePath() {
  return window['go']['main']['App']['ChooseXPlanePath']();
}

export function ClaimOwnership(arg1) {
  return window['go']['main']['App']['ClaimOwnership'](arg1);
}

export function CreateSession(arg1, arg2) {
  return window['go']['main']['App']['CreateSession'](arg1, arg2);
}

export function DeleteSavedServer(arg1) {
  return window['go']['main']['App']['DeleteSavedServer'](arg1);
}

export function DisconnectFormation() {
  return window['go']['main']['App']['DisconnectFormation']();
}

export function DisconnectSharedCockpit() {
  return window['go']['main']['App']['DisconnectSharedCockpit']();
}

export function GetAvailablePluginVersion() {
  return window['go']['main']['App']['GetAvailablePluginVersion']();
}

export function GetInstalledPluginVersion() {
  return window['go']['main']['App']['GetInstalledPluginVersion']();
}

export function GetRecentLogLines(arg1) {
  return window['go']['main']['App']['GetRecentLogLines'](arg1);
}

export function GetSavedServers() {
  return window['go']['main']['App']['GetSavedServers']();
}

export function GetXPlanePath() {
  return window['go']['main']['App']['GetXPlanePath']();
}

export function InstallPlugin() {
  return window['go']['main']['App']['InstallPlugin']();
}

export function JoinSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['JoinSession'](arg1, arg2, arg3);
}

export function ReloadCsl() {
  return window['go']['main']['App']['ReloadCsl']();
}

export function SaveServer(arg1, arg2) {
  return window['go']['main']['App']['SaveServer'](arg1, arg2);
}

export function StartSharedCockpit(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartSharedCockpit'](arg1, arg2, arg3);
}
