// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFlightEvent(arg1, arg2) {
  return window['go']['main']['App']['AddFlightEvent'](arg1, arg2);
}

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ChooseXPlanePath() {
  return window['go']['main']['App']['ChooseXPlanePath']();
}

export function ClaimOwnership(arg1) {
  return window['go']['main']['App']['ClaimOwnership'](arg1);
}

export function ClearSharedRoute() {
  return window['go']['main']['App']['ClearSharedRoute']();
}

export function CreateSession(arg1, arg2) {
  return window['go']['main']['App']['CreateSession'](arg1, arg2);
}

export function DeleteFlight(arg1) {
  return window['go']['main']['App']['DeleteFlight'](arg1);
}

export function DeleteLanding(arg1) {
  return window['go']['main']['App']['DeleteLanding'](arg1);
}

export function DeleteSavedServer(arg1) {
  return window['go']['main']['App']['DeleteSavedServer'](arg1);
}

export function DeleteUserChecklists(arg1) {
  return window['go']['main']['App']['DeleteUserChecklists'](arg1);
}

export function DeleteUserProfile(arg1) {
  return window['go']['main']['App']['DeleteUserProfile'](arg1);
}

export function DisconnectFormation() {
  return window['go']['main']['App']['DisconnectFormation']();
}

export function DisconnectSharedCockpit() {
  return window['go']['main']['App']['DisconnectSharedCockpit']();
}

export function ExportFms(arg1) {
  return window['go']['main']['App']['ExportFms'](arg1);
}

export function GetAirportInfo(arg1) {
  return window['go']['main']['App']['GetAirportInfo'](arg1);
}

export function GetAirportLayout(arg1) {
  return window['go']['main']['App']['GetAirportLayout'](arg1);
}

export function GetAirports() {
  return window['go']['main']['App']['GetAirports']();
}

export function GetAirspaces(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetAirspaces'](arg1, arg2, arg3, arg4);
}

export function GetAvailablePluginVersion() {
  return window['go']['main']['App']['GetAvailablePluginVersion']();
}

export function GetDuplicatePluginInstalls() {
  return window['go']['main']['App']['GetDuplicatePluginInstalls']();
}

export function GetInstalledPluginVersion() {
  return window['go']['main']['App']['GetInstalledPluginVersion']();
}

export function GetLandingBoard() {
  return window['go']['main']['App']['GetLandingBoard']();
}

export function GetLastPage() {
  return window['go']['main']['App']['GetLastPage']();
}

export function GetNavCollapsed() {
  return window['go']['main']['App']['GetNavCollapsed']();
}

export function GetNavData() {
  return window['go']['main']['App']['GetNavData']();
}

export function GetPrefs() {
  return window['go']['main']['App']['GetPrefs']();
}

export function GetRecentLogLines(arg1) {
  return window['go']['main']['App']['GetRecentLogLines'](arg1);
}

export function GetSavedServers() {
  return window['go']['main']['App']['GetSavedServers']();
}

export function GetXPlanePath() {
  return window['go']['main']['App']['GetXPlanePath']();
}

export function ImportFms() {
  return window['go']['main']['App']['ImportFms']();
}

export function InstallPlugin() {
  return window['go']['main']['App']['InstallPlugin']();
}

export function JoinSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['JoinSession'](arg1, arg2, arg3);
}

export function ListFlights() {
  return window['go']['main']['App']['ListFlights']();
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function LoadChecklists(arg1) {
  return window['go']['main']['App']['LoadChecklists'](arg1);
}

export function LoadFlight(arg1) {
  return window['go']['main']['App']['LoadFlight'](arg1);
}

export function LoadProfile(arg1) {
  return window['go']['main']['App']['LoadProfile'](arg1);
}

export function NearestAirports(arg1, arg2) {
  return window['go']['main']['App']['NearestAirports'](arg1, arg2);
}

export function ReloadCsl() {
  return window['go']['main']['App']['ReloadCsl']();
}

export function SaveChecklists(arg1, arg2) {
  return window['go']['main']['App']['SaveChecklists'](arg1, arg2);
}

export function SaveProfile(arg1, arg2) {
  return window['go']['main']['App']['SaveProfile'](arg1, arg2);
}

export function SaveServer(arg1, arg2) {
  return window['go']['main']['App']['SaveServer'](arg1, arg2);
}

export function ScResync() {
  return window['go']['main']['App']['ScResync']();
}

export function SearchAirports(arg1) {
  return window['go']['main']['App']['SearchAirports'](arg1);
}

export function SearchDatarefs(arg1) {
  return window['go']['main']['App']['SearchDatarefs'](arg1);
}

export function SetChecklistWatch(arg1) {
  return window['go']['main']['App']['SetChecklistWatch'](arg1);
}

export function SetLastPage(arg1) {
  return window['go']['main']['App']['SetLastPage'](arg1);
}

export function SetNavCollapsed(arg1) {
  return window['go']['main']['App']['SetNavCollapsed'](arg1);
}

export function SetPrefs(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SetPrefs'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ShareChecklistState(arg1) {
  return window['go']['main']['App']['ShareChecklistState'](arg1);
}

export function ShareRoute(arg1) {
  return window['go']['main']['App']['ShareRoute'](arg1);
}

export function StartLearn() {
  return window['go']['main']['App']['StartLearn']();
}

export function StartSharedCockpit(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartSharedCockpit'](arg1, arg2, arg3);
}

export function StopLearn() {
  return window['go']['main']['App']['StopLearn']();
}

export function SyncEnv() {
  return window['go']['main']['App']['SyncEnv']();
}
