// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddFlightEvent(arg1:string,arg2:string):Promise<void>;

export function ApplyUpdate():Promise<void>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function ChooseXPlanePath():Promise<main.ChooseXPlaneResult>;

export function ClaimOwnership(arg1:string):Promise<void>;

export function ClearSharedRoute():Promise<void>;

export function CreateSession(arg1:string,arg2:boolean):Promise<void>;

export function DeleteFlight(arg1:string):Promise<void>;

export function DeleteLanding(arg1:string):Promise<void>;

export function DeleteSavedServer(arg1:string):Promise<void>;

export function DeleteTour(arg1:string):Promise<void>;

export function DeleteUserChecklists(arg1:string):Promise<void>;

export function DeleteUserProfile(arg1:string):Promise<void>;

export function DisconnectFormation():Promise<void>;

export function DisconnectSharedCockpit():Promise<void>;

export function ExportFms(arg1:main.PlannedRoute):Promise<string>;

export function GenerateTour(arg1:main.TourRequest):Promise<main.Tour>;

export function GetAirportInfo(arg1:string):Promise<main.AirportInfo>;

export function GetAirportLayout(arg1:string):Promise<main.AirportLayout>;

export function GetAirports():Promise<main.AirportData>;

export function GetAirspaces(arg1:number,arg2:number,arg3:number,arg4:number):Promise<Array<main.Airspace>>;

export function GetAvailablePluginVersion():Promise<string>;

export function GetDuplicatePluginInstalls():Promise<Array<string>>;

export function GetInstalledPluginVersion():Promise<string>;

export function GetLandingBoard():Promise<main.LandingBoard>;

export function GetLastPage():Promise<string>;

export function GetLogbook():Promise<main.Logbook>;

export function GetNavCollapsed():Promise<boolean>;

export function GetNavData():Promise<main.NavData>;

export function GetPrefs():Promise<main.PluginPrefs>;

export function GetRecentLogLines(arg1:number):Promise<main.LogLinesResult>;

export function GetRouteBriefing(arg1:main.PlannedRoute):Promise<main.RouteBriefing>;

export function GetRouteSights(arg1:main.PlannedRoute):Promise<Array<main.Sight>>;

export function GetSavedServers():Promise<Array<main.SavedServer>>;

export function GetXPlanePath():Promise<string>;

export function ImportFms():Promise<main.PlannedRoute>;

export function ImportTourCode(arg1:string):Promise<main.Tour>;

export function InstallPlugin():Promise<void>;

export function JoinSession(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function ListFlights():Promise<Array<main.FlightSummary>>;

export function ListProfiles():Promise<Array<main.ProfileInfo>>;

export function ListTours():Promise<Array<main.Tour>>;

export function LoadChecklists(arg1:string):Promise<main.ChecklistFile>;

export function LoadFlight(arg1:string):Promise<main.Flight>;

export function LoadProfile(arg1:string):Promise<main.ProfileData>;

export function NearestAirports(arg1:number,arg2:number):Promise<Array<main.AirportHit>>;

export function PlanAutoRoute(arg1:main.AutoRouteRequest):Promise<main.AutoRouteResult>;

export function ReloadCsl():Promise<void>;

export function SaveChecklists(arg1:string,arg2:string):Promise<main.ChecklistFile>;

export function SaveProfile(arg1:string,arg2:Array<main.ProfileEntry>):Promise<main.ProfileData>;

export function SaveServer(arg1:string,arg2:string):Promise<void>;

export function SaveTour(arg1:main.Tour):Promise<main.Tour>;

export function ScResync():Promise<void>;

export function SearchAirports(arg1:string):Promise<Array<main.AirportHit>>;

export function SearchDatarefs(arg1:string):Promise<Array<main.DatarefInfo>>;

export function SetApproachCoach(arg1:boolean):Promise<void>;

export function SetChecklistWatch(arg1:Array<string>):Promise<void>;

export function SetLastPage(arg1:string):Promise<void>;

export function SetNavCollapsed(arg1:boolean):Promise<void>;

export function SetPrefs(arg1:string,arg2:boolean,arg3:boolean,arg4:boolean,arg5:boolean,arg6:boolean):Promise<main.PluginPrefs>;

export function ShareChecklistState(arg1:string):Promise<void>;

export function ShareRoute(arg1:main.PlannedRoute):Promise<void>;

export function StartLearn():Promise<void>;

export function StartSharedCockpit(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StopLearn():Promise<void>;

export function SuggestDestinations(arg1:main.DestinationRequest):Promise<main.DestinationIdeas>;

export function SyncEnv():Promise<void>;

export function TourLegSights(arg1:main.Tour):Promise<Array<any>>;

export function TourShareCode(arg1:main.Tour):Promise<string>;
