// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyUpdate():Promise<void>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function ChooseXPlanePath():Promise<main.ChooseXPlaneResult>;

export function ClaimOwnership(arg1:string):Promise<void>;

export function CreateSession(arg1:string,arg2:boolean):Promise<void>;

export function DeleteSavedServer(arg1:string):Promise<void>;

export function DisconnectFormation():Promise<void>;

export function DisconnectSharedCockpit():Promise<void>;

export function GetAvailablePluginVersion():Promise<string>;

export function GetInstalledPluginVersion():Promise<string>;

export function GetRecentLogLines(arg1:number):Promise<main.LogLinesResult>;

export function GetSavedServers():Promise<Array<main.SavedServer>>;

export function GetXPlanePath():Promise<string>;

export function InstallPlugin():Promise<void>;

export function JoinSession(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function ReloadCsl():Promise<void>;

export function SaveServer(arg1:string,arg2:string):Promise<void>;

export function StartSharedCockpit(arg1:string,arg2:string,arg3:string):Promise<void>;
