// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseXPlanePath() {
  return window['go']['main']['App']['ChooseXPlanePath']();
}

export function CreateSession(arg1) {
  return window['go']['main']['App']['CreateSession'](arg1);
}

export function DisconnectFormation() {
  return window['go']['main']['App']['DisconnectFormation']();
}

export function DisconnectSharedCockpit() {
  return window['go']['main']['App']['DisconnectSharedCockpit']();
}

export function GetAvailablePluginVersion() {
  return window['go']['main']['App']['GetAvailablePluginVersion']();
}

export function GetInstalledPluginVersion() {
  return window['go']['main']['App']['GetInstalledPluginVersion']();
}

export function GetXPlanePath() {
  return window['go']['main']['App']['GetXPlanePath']();
}

export function InstallPlugin() {
  return window['go']['main']['App']['InstallPlugin']();
}

export function JoinSession(arg1, arg2) {
  return window['go']['main']['App']['JoinSession'](arg1, arg2);
}

export function StartSharedCockpit(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartSharedCockpit'](arg1, arg2, arg3);
}
