package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

const sampleAptDat = `I
1200 Generated by WorldEditor

1   364 0 0 EDDF Frankfurt am Main
1302 datum_lat 50.033333
1302 datum_lon 8.570556
100 60.00 1 0 0.25 1 1 1 07C  50.03253798  8.53459410    0.00  150.00 3 10 1 1 25C  50.04499797  8.58696597    0.00  150.00 3 10 1 1
1   1 0 0 XNOD No Datum Strip
100 20.00 3 0 0.25 0 0 0 09  10.0 20.0 0 0 0 0 0 0 27  10.0 20.2 0 0 0 0 0 0
16  0 0 0 SEA1 Some Seaplane Base
101 49 1 04 47.0 -122.0 22 47.2 -122.2
17  10 0 0 H1 A Heliport
102 H1 33.5 -117.5 0 10 10 1 0 0 0 0
99
`

func TestParseAptDat(t *testing.T) {
	data, err := parseAptDat(strings.NewReader(sampleAptDat))
	if err != nil {
		t.Fatal(err)
	}
	if len(data.Airports) != 4 {
		t.Fatalf("expected 4 airports, got %+v", data.Airports)
	}
	eddf := data.Airports[0]
	if eddf[0] != "EDDF" || eddf[1] != "Frankfurt am Main" || eddf[2] != 50.033333 || eddf[3] != 8.570556 || eddf[4] != 1 {
		t.Fatalf("EDDF parsed wrong: %+v", eddf)
	}
	if nd := data.Airports[1]; nd[2] != 10.0 || nd[3] != 20.1 {
		t.Fatalf("airport without datum should sit at its runway midpoint, got %+v", nd)
	}
	if sea := data.Airports[2]; sea[2] != 47.1 || sea[3] != -122.1 || sea[4] != 16 {
		t.Fatalf("seaplane base parsed wrong: %+v", sea)
	}
	if heli := data.Airports[3]; heli[2] != 33.5 || heli[3] != -117.5 || heli[4] != 17 {
		t.Fatalf("heliport parsed wrong: %+v", heli)
	}
	if len(data.Runways) != 2 || data.Runways[0] != [4]float64{50.032538, 8.534594, 50.044998, 8.586966} {
		t.Fatalf("unexpected runways: %+v", data.Runways)
	}
}

func TestLoadAirportsCaches(t *testing.T) {
	root := t.TempDir()
	cache := t.TempDir()
	old := userCacheDir
	userCacheDir = func() (string, error) { return cache, nil }
	t.Cleanup(func() { userCacheDir = old })

	if _, err := loadAirports(root); err == nil {
		t.Fatal("expected an error without apt.dat")
	}
	path := aptDatPath(root)
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(sampleAptDat), 0644); err != nil {
		t.Fatal(err)
	}
	first, err := loadAirports(root)
	if err != nil || len(first.Airports) != 4 {
		t.Fatalf("first load: %+v %v", first, err)
	}
	if _, err := os.Stat(filepath.Join(cache, "xpmulticrew-companion", "airports.json")); err != nil {
		t.Fatalf("expected a cache file: %v", err)
	}
	// A changed apt.dat (new size/mtime) must invalidate the cache.
	later := time.Now().Add(time.Hour)
	if err := os.WriteFile(path, []byte(strings.Replace(sampleAptDat, "EDDF", "EDDX", 1)), 0644); err != nil {
		t.Fatal(err)
	}
	_ = os.Chtimes(path, later, later)
	second, err := loadAirports(root)
	if err != nil || second.Airports[0][0] != "EDDX" {
		t.Fatalf("cache not invalidated: %+v %v", second.Airports, err)
	}
}
